# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:8080


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["sar-data-api/sar-data-api.csproj", "sar-data-api/"]
COPY ["DDO.SarInfo/DDO.SarInfo.csproj", "DDO.SarInfo/"]
COPY ["TNA.RepositoryLibraries.MongoDBEntities/TNA.RepositoryLibraries.MongoDBEntities.csproj", "TNA.RepositoryLibraries.MongoDBEntities/"]
COPY ["Repositories.SarInfo/Repositories.SarInfo.csproj", "Repositories.SarInfo/"]
COPY ["RepositoryContracts.Sar/RepositoryContracts.SarInfo.csproj", "RepositoryContracts.Sar/"]
COPY ["TNA.RepositoryLibraries.MongoDB/TNA.RepositoryLibraries.MongoDB.csproj", "TNA.RepositoryLibraries.MongoDB/"]
RUN dotnet restore "./sar-data-api/sar-data-api.csproj"
COPY . .
WORKDIR "/src/sar-data-api"
RUN dotnet build "./sar-data-api.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./sar-data-api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
RUN addgroup -g 965 -S appuser && adduser -u 975 -S -D -h /app appuser appuser
USER appuser
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "sar-data-api.dll"]