# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:8080

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["ia-data-api/ia-data-api.csproj", "ia-data-api/"]
COPY ["DDO.FAInformationAsset/DDO.FAInformationAsset.csproj", "DDO.FAInformationAsset/"]
COPY ["DDO.InformationAsset/DDO.InformationAsset.csproj", "DDO.InformationAsset/"]
COPY ["TNA.RepositoryLibraries.MongoDBEntities/TNA.RepositoryLibraries.MongoDBEntities.csproj", "TNA.RepositoryLibraries.MongoDBEntities/"]
COPY ["Repositories.FAInformationAsset/Repositories.FAInformationAsset.csproj", "Repositories.FAInformationAsset/"]
COPY ["RepositoryContracts.FAInformationAsset/RepositoryContracts.FAInformationAsset.csproj", "RepositoryContracts.FAInformationAsset/"]
COPY ["TNA.RepositoryLibraries.MongoDB/TNA.RepositoryLibraries.MongoDB.csproj", "TNA.RepositoryLibraries.MongoDB/"]
COPY ["Repositories.InformationAsset/Repositories.InformationAsset.csproj", "Repositories.InformationAsset/"]
COPY ["RepositoryContracts.InformationAsset/RepositoryContracts.InformationAsset.csproj", "RepositoryContracts.InformationAsset/"]
RUN dotnet restore "./ia-data-api/ia-data-api.csproj"
COPY . .
WORKDIR "/src/ia-data-api"
RUN dotnet build "./ia-data-api.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./ia-data-api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
RUN addgroup -g 965 -S appuser && adduser -u 975 -S -D -h /app appuser appuser
USER appuser
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ia-data-api.dll"]