# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:8080

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["meta-data-api/meta-data-api.csproj", "meta-data-api/"]
COPY ["Repositories.PreparedFile/Repositories.PreparedFile.csproj", "Repositories.PreparedFile/"]
COPY ["DDO.PreparedFile/DDO.PreparedFile.csproj", "DDO.PreparedFile/"]
COPY ["TNA.RepositoryLibraries.MongoDBEntities/TNA.RepositoryLibraries.MongoDBEntities.csproj", "TNA.RepositoryLibraries.MongoDBEntities/"]
COPY ["RepositoryContracts.PreparedFile/RepositoryContracts.PreparedFile.csproj", "RepositoryContracts.PreparedFile/"]
COPY ["TNA.RepositoryLibraries.MongoDB/TNA.RepositoryLibraries.MongoDB.csproj", "TNA.RepositoryLibraries.MongoDB/"]
COPY ["Repositories.ReplicaEditSet/Repositories.ReplicaEditSet.csproj", "Repositories.ReplicaEditSet/"]
COPY ["RepositoryContracts.ReplicaEditSet/RepositoryContracts.ReplicaEditSet.csproj", "RepositoryContracts.ReplicaEditSet/"]
COPY ["DDO.ReplicaEditSet/DDO.ReplicaEditSet.csproj", "DDO.ReplicaEditSet/"]
COPY ["Repositories.Replica/Repositories.Replica.csproj", "Repositories.Replica/"]
COPY ["RepositoryContracts.Replica/RepositoryContracts.Replica.csproj", "RepositoryContracts.Replica/"]
COPY ["DDO.Replica/DDO.Replica.csproj", "DDO.Replica/"]
RUN dotnet restore "./meta-data-api/meta-data-api.csproj"
COPY . .
WORKDIR "/src/meta-data-api"
RUN dotnet build "./meta-data-api.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./meta-data-api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
RUN addgroup -g 965 -S appuser && adduser -u 975 -S -D -h /app appuser appuser
USER appuser
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "meta-data-api.dll"]