///////////////////////////////////////////////////////////
//  File.cs
//  Implementation of the Class File
//  Generated by Enterprise Architect
//  Created on:      04-Aug-2017 10:49:13
//  Original author: voliynyk
///////////////////////////////////////////////////////////

using MongoDB.Bson.Serialization.Attributes;

namespace TNA.DataDefinitionObjects
{
    public class DFile
    {
        /// <summary>
        /// Checksum of each individual file calculated at the time of transfer.
        /// </summary>
        [BsonIgnoreIfDefault]
        public string CSum { get; set; }

        /// <summary>
        /// File format: jpg, pdf, etc.
        /// </summary>
        public string Frmt { get; set; }

        /// <summary>
        /// Presentation file name and path in S3. I.e. "66\KV\2\0000-0000-0000-0000.pdf"
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Original file name. As it is stored at the source.
        /// </summary>
        [BsonIgnoreIfDefault]
        public string OrigName { get; set; }

        /// <summary>
        /// File size in KB
        /// </summary>
        public int Size { get; set; }
    }//end File
}//end namespace DigitalReplica