///////////////////////////////////////////////////////////
//  Origination.cs
//  Implementation of the Class Origination
//  Generated by Enterprise Architect
//  Created on:      04-Aug-2017 10:49:28
//  Original author: voliynyk
///////////////////////////////////////////////////////////

namespace TNA.DataDefinitionObjects
{
    public enum Origination : int
    {
        DigitalSurrogate = 0,
        Digitised = 1,
        BornDigital = 2
    }//end Origination
}//end namespace DigitalReplica