///////////////////////////////////////////////////////////
//  Replica.cs
//  Implementation of the Class Replica
//  Generated by Enterprise Architect
//  Created on:      04-Aug-2017 10:49:30
//  Original author: voliynyk
///////////////////////////////////////////////////////////

using MongoDB.Bson.Serialization.Attributes;
using System.Collections.Generic;
using TNA.RepositoryLibraries.MongoDB;
using TNA.RepositoryLibraries.MongoDBEntities;

namespace TNA.DataDefinitionObjects
{
    [ConnectionName("ReplicaConnection")]
    [CollectionName("Replica")]
    public class Repl : Entity
    {
        public List<DFile> Files { get; set; }

        /// <summary>
        /// Replica ID
        /// </summary>
        public string RID { get; set; }

        /// <summary>
        /// How related digital files were created: digitized or born digital
        /// </summary>
        [BsonIgnoreIfDefault]
        public Origination Orig { get; set; }

        /// <summary>
        /// A sum of all files sizes within this Replica
        /// </summary>
        public int TSize { get; set; }
    }//end Replica
}//end namespace DigitalReplica